name: modem-manager
version: 1.6.2-4
summary: ModemManager is a service which controls mobile broadband
description: |
  ModemManager is a DBus-activated daemon which controls mobile broadband
  (2G/3G/4G) devices and connections. Whether built-in devices, USB dongles,
  bluetooth-paired telephones or professional RS232/USB devices with external
  power supplies, ModemManager is able to prepare and configure the modems and
  setup connections with them.
  Please find the source code at https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager
confinement: strict
grade: stable

slots:
  service: modem-manager

plugs:
  mmcli: modem-manager

apps:
  mmcli:
    command: bin/mmcli
    plugs: [mmcli]
    aliases:
      - mmcli
  modemmanager:
    command: bin/modemmanager
    daemon: simple
    slots: [service]

parts:
  modemmanager-common:
    plugin: copy
    files:
      bin/modemmanager: bin/modemmanager
      bin/mmcli: bin/mmcli
      data/copyright: usr/share/doc/modem-manager/copyright

  libmbim:
    plugin: autotools

    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager
    source-type: git
    source-branch: libmbim/xenial/1.14.0

    configflags:
      - --with-udev
      - --libexecdir=/usr/lib/libmbim

    build-packages:
      - libglib2.0-dev
      - libgudev-1.0-dev

    filesets:
      wanted:
        - lib/libmbim-glib.so*
        - usr/lib/libmbim/mbim-proxy

    prime:
      - $wanted

  libqmi:
    after: [ libmbim ]
    plugin: autotools

    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager
    source-type: git
    source-branch: libqmi/xenial/1.16.2

    configflags:
      - --enable-mbim-qmux
      - --libexecdir=/usr/lib/libqmi

    build-packages:
      - intltool
      - libglib2.0-dev

    filesets:
      wanted:
        - lib/libqmi-glib.so*
        - usr/lib/libqmi/qmi-proxy

    prime:
      - $wanted

  modemmanager:
    after: [ libmbim, libqmi ]
    plugin: autotools

    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager
    source-type: git
    source-branch: modem-manager/xenial/1.6.2

    configflags:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --libexecdir=/usr/lib/ModemManager
      - --sysconfdir=/etc
      - --enable-gtk-doc=no
      - --with-polkit=no
      - --enable-vala=no
      - --enable-tests=yes

    build-packages:
      - intltool
      - gtk-doc-tools
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libiw-dev
      - libglib2.0-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - libnss3-dev
      - libgnutls28-dev
      - libgcrypt11-dev
      - libxml-parser-perl
      - uuid-dev
      - libsystemd-dev
      - libudev-dev
      - libgudev-1.0-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - libsoup2.4-dev
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - dbus-test-runner
      - python-dbus
      - python-gi

    stage-packages:
      - automake
      - libtool
      - intltool
      - gtk-doc-tools
      - gnome-common
      - gobject-introspection
      - libgirepository1.0-dev
      - libglib2.0-dev
      - libgudev-1.0-dev
      - libglib2.0-doc

    install: |
      # Run all tests ModemManager ships by default
      make check

    filesets:
      wanted:
        - usr/bin/mmcli
        - usr/sbin/ModemManager
        - usr/lib/ModemManager/
        - usr/lib/*/libgudev-1.0.so*
        - usr/lib/libmm-glib.so*
        - usr/share/doc/libgudev-1.0-0/
        # Following libraries could also be pulled from core
        - usr/lib/*/libgmodule-2.0.so*
        - usr/lib/*/libgio-2.0.so*
        - usr/lib/*/libgobject-2.0.so*
        - usr/lib/*/libglib-2.0.so*
        - usr/lib/*/libffi.so*
        - usr/lib/*/libpcre.so*
        - lib/*/libglib-2.0.so*
        - lib/*/libpcre.so*
        - usr/share/doc/libglib2.0-*
        - usr/share/doc/libffi6/
        - usr/share/doc/libpcre*

    prime:
      - $wanted
