name: modem-manager
version: 1.18.6-2
summary: ModemManager is a service which controls mobile broadband
description: |
  ModemManager is a DBus-activated daemon which controls mobile broadband
  (2G/3G/4G) devices and connections. Whether built-in devices, USB dongles,
  bluetooth-paired telephones or professional RS232/USB devices with external
  power supplies, ModemManager is able to prepare and configure the modems and
  setup connections with them.
  Please find the source code at
  https://code.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/modem-manager/+ref/snap-22
confinement: strict
grade: stable
base: core22

slots:
  service: modem-manager

plugs:
  mmcli: modem-manager

hooks:
  configure:
    plugs: [mmcli]

layout:
  /usr/lib/ModemManager:
    symlink: $SNAP/usr/lib/ModemManager
  /usr/libexec/qmi-proxy:
    symlink: $SNAP/usr/libexec/qmi-proxy
  /usr/libexec/mbim-proxy:
    symlink: $SNAP/usr/libexec/mbim-proxy

apps:
  mmcli:
    command: bin/mmcli
    plugs: [mmcli]
  modemmanager:
    command: bin/modemmanager
    daemon: simple
    slots: [service]
  mbimcli:
    command: usr/bin/mbimcli
    slots: [service]
  mbim-network:
    command: usr/bin/mbim-network
    slots: [service]
  qmicli:
    command: usr/bin/qmicli
    slots: [service]
  qmi-network:
    command: usr/bin/qmi-network
    slots: [service]

parts:
  modemmanager-hooks:
    plugin: dump
    source: hooks
    organize:
      configure: meta/hooks/configure

  modemmanager-bin:
    plugin: dump
    source: bin
    organize:
      modemmanager: bin/modemmanager
      mmcli: bin/mmcli
      mmcli-internal: bin/mmcli-internal

  changelog:
    plugin: nil
    override-build: |
      cp "$SNAPCRAFT_PROJECT_DIR"/ChangeLog "$SNAPCRAFT_PART_INSTALL"
    organize:
      ChangeLog: snap/ChangeLog

  # Get aux scripts so they can be used in other parts. Also, stage
  # packages we rebuild later to get copyright and ensure they are in
  # the manifest.
  stack-snaps-tools:
    plugin: nil
    source: https://git.launchpad.net/~snappy-hwe-team/snappy-hwe-snaps/+git/stack-snaps-tools
    source-type: git
    build-packages:
      - dpkg-dev
      - git
    stage-packages:
      - modemmanager
      - libmm-glib0
    override-build: |
      set -ex
      find "$SNAPCRAFT_PART_INSTALL"/ -type f,l \
                -not -path "$SNAPCRAFT_PART_INSTALL"/'usr/share/doc/modemmanager*' \
           -and -not -path "$SNAPCRAFT_PART_INSTALL"/'usr/share/doc/libmm-glib0*' \
           -delete
      find "$SNAPCRAFT_PART_INSTALL"/ -type d -empty -delete
      mkdir -p "$SNAPCRAFT_PART_INSTALL"/build-tools
      cp build-tools/* "$SNAPCRAFT_PART_INSTALL"/build-tools
    prime:
      - usr/share/doc/modemmanager
      - usr/share/doc/libmm-glib0

  modemmanager:
    plugin: autotools
    after: [ stack-snaps-tools ]

    source: https://git.launchpad.net/ubuntu/+source/modemmanager
    source-type: git
    source-branch: applied/ubuntu/jammy

    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib
      - --libexecdir=/usr/lib/ModemManager
      - --sysconfdir=/etc
      - --enable-gtk-doc=no
      - --with-polkit=no
      - --enable-vala=no
      - --disable-maintainer-mode
      # Set explicitly CFLAGS until lp: #1791946 is solved
      - CFLAGS=-O2

    build-packages:
      - autoconf-archive
      - intltool
      - gtk-doc-tools
      - libdbus-glib-1-dev
      - libdbus-1-dev
      - libiw-dev
      - libglib2.0-dev
      - libnl-3-dev
      - libnl-route-3-dev
      - libnl-genl-3-dev
      - libnss3-dev
      - libgnutls28-dev
      - libxml-parser-perl
      - uuid-dev
      - libsystemd-dev
      - libudev-dev
      - libgudev-1.0-dev
      - libgirepository1.0-dev
      - gobject-introspection
      - libsoup2.4-dev
      - libglib2.0-doc
      - libmm-glib-dev
      - libndp-dev
      - libreadline-dev
      - libnewt-dev
      - dbus-test-runner
      - python3-dbus
      - python3-gi
      - libqmi-glib-dev
      - libmbim-glib-dev

    stage-packages:
      - libqmi-glib5
      - libqmi-proxy
      - libqmi-utils
      - libmbim-glib4
      - libmbim-proxy
      - libmbim-utils
      - libgudev-1.0-0

    override-build: |
      set -ex
      "$SNAPCRAFT_STAGE"/build-tools/check-versions modemmanager
      # Apply snap related patches
      git config user.email "snapcraft@canonical.com"
      git config user.name "snapcraft"
      git am "$SNAPCRAFT_PROJECT_DIR"/patch/*.patch
      # Build (rename .git so configure sets release flag)
      mv .git git
      snapcraftctl build
      # Run all tests ModemManager ships by default
      make check
      mv git .git
      # Strip binaries
      find "$SNAPCRAFT_PART_INSTALL"/ -executable -type f | xargs file -Ni |
          grep 'application/x-executable\|application/x-sharedlib' | cut -d: -f1 | xargs strip

    filesets:
      wanted:
        - usr/bin/mmcli
        - usr/sbin/ModemManager
        - usr/lib/ModemManager/*so
        - usr/lib/*/libgudev-1.0.so*
        - usr/lib/libmm-glib.so*
        - usr/share/doc/libgudev-1.0-0
        - usr/lib/*/libmbim-glib.so*
        - usr/bin/mbimcli
        - usr/bin/mbim-network
        - usr/share/doc/libmbim-glib4
        - usr/share/doc/libmbim-proxy
        - usr/share/doc/libmbim-utils
        - usr/lib/*/libqmi-glib.so*
        - usr/bin/qmicli
        - usr/bin/qmi-firmware-update
        - usr/bin/qmi-network
        - usr/share/doc/libqmi-glib5
        - usr/share/doc/libqmi-proxy
        - usr/share/doc/libqmi-utils
        - usr/libexec/*

    prime:
      - $wanted
